/** Node-only access to the derived handwriting dataset (data/uji-upper.json, generated by `pnpm hw:data`). */
import { existsSync, readFileSync } from 'node:fs';
import type { Sample } from '../src/handwriting';

export const DATA_PATH = 'data/uji-upper.json';

export function loadSamples(): Sample[] {
  if (!existsSync(DATA_PATH)) throw new Error(`${DATA_PATH} is missing: run \`pnpm hw:data\` first`);
  const raw = JSON.parse(readFileSync(DATA_PATH, 'utf8')) as { samples: Array<{ w: string; l: number; s: number[][] }> };
  return raw.samples.map((s) => ({ writer: s.w, label: s.l, strokes: s.s }));
}
